ALTER TABLE weather
 ADD createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  AFTER date,
 ADD updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  AFTER createdAt,
 ADD deletedAt TIMESTAMP NULL DEFAULT NULL
  AFTER updatedAt;